### ISSUE TITLE
Error loading package

### ISSUE THREAD

**Issue by v-gold** [juliandehne/delab-trees#1]
When I run the example as given on the webpage, the package executes with the following error: 

```
>>> import pandas as pd
>>> from delab_trees import TreeManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vgold/opt/anaconda3/envs/r-reticulate/lib/python3.8/site-packages/delab_trees/__init__.py", line 1, in <module>
    from .main import TreeManager
  File "/Users/vgold/opt/anaconda3/envs/r-reticulate/lib/python3.8/site-packages/delab_trees/main.py", line 9, in <module>
    from delab_trees.delab_tree import DelabTree
  File "/Users/vgold/opt/anaconda3/envs/r-reticulate/lib/python3.8/site-packages/delab_trees/delab_tree.py", line 16, in <module>
    from delab_trees.flow_duos import compute_highest_flow_delta, FLowDuo
  File "/Users/vgold/opt/anaconda3/envs/r-reticulate/lib/python3.8/site-packages/delab_trees/flow_duos.py", line 71, in <module>
    def compute_highest_flow_delta(candidate_flows: list[(str, list[DelabPost])], metric: str, min_post_branching: int,
TypeError: 'type' object is not subscriptable
```

I'm running Anaconda-Python, version 3.8.8 on Mac OS.

**Comment by juliandehne** [comment]
Could not reproduce with python 3.10 (recommended version in pypy). Can you upgrade or should I make it compatible to 3.8?

**Comment by v-gold** [comment]
Upgrading Python solves the issue. Thanks.
